"""add_import_process_id_to_step_model

Revision ID: 2eed081b3371
Revises: 2662965e3ddc
Create Date: 2025-06-06 15:58:09.982930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eed081b3371'
down_revision = '2662965e3ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_process_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_step_import_process', 'import_process', ['import_process_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_constraint('fk_step_import_process', type_='foreignkey')
        batch_op.drop_column('import_process_id')

    # ### end Alembic commands ###
